[package]
name = "bevy_quicsilver"
version = "0.1.0"
authors = ["Pixelstorm"]
edition = "2021"
description = "Implementation of the QUIC transport protocol for bevy_ecs, using quinn_proto"
repository = "https://github.com/Pixelstormer/bevy_quicsilver"
license = "Apache-2.0"
keywords = ["bevy", "quic", "gamedev", "networking"]
categories = ["game-development", "network-programming"]

[dependencies]
bevy_app = { version = "0.13", default-features = false }
bevy_ecs = { version = "0.13", default-features = false }
bevy_time = { version = "0.13", default-features = false }
hashbrown = "0.14"
bytes = "1.6"
thiserror = "1.0"
quinn-proto = { version = "0.11", default-features = false, features = ["rustls"] }
quinn-udp = { version = "0.5", default-features = false }
rustls = { version = "0.23", default-features = false, features = ["logging", "std"] }
rcgen = { version = "0.13", default-features = false, features = ["crypto", "ring"] }
tracing = { version = "0.1", default-features = false, features = ["std"] }

[features]
default = ["platform-verifier"]
platform-verifier = ["quinn-proto/platform-verifier"]
