[package]
name = "bevy_quicsilver"
version = "0.1.1"
authors = ["BigWingBeat"]
edition = "2021"
description = "Implementation of the QUIC transport protocol for bevy_ecs, using quinn_proto"
repository = "https://github.com/BigWingBeat/bevy_quicsilver"
license = "Apache-2.0"
keywords = ["bevy", "quic", "gamedev", "networking"]
categories = ["game-development", "network-programming"]

[dependencies]
bevy_app = { git = "https://github.com/BigWingBeat/bevy", branch = "fork-main", default-features = false }
bevy_ecs = { git = "https://github.com/BigWingBeat/bevy", branch = "fork-main", default-features = false }
bevy_time = { git = "https://github.com/BigWingBeat/bevy", branch = "fork-main", default-features = false }
hashbrown = "0.14"
bytes = "1.6"
thiserror = "1.0"
quinn-proto = { version = "0.11", default-features = false, features = ["rustls"] }
quinn-udp = { version = "0.5", default-features = false }
rustls = { version = "0.23", default-features = false, features = ["logging", "std"] }
rcgen = { version = "0.13", default-features = false, features = ["crypto", "ring"] }

[dev-dependencies]
directories = "5.0"
bevy_state = { git = "https://github.com/BigWingBeat/bevy", branch = "fork-main", default-features = false, features = [
	"bevy_app",
] }

[features]
default = ["platform-verifier"]
platform-verifier = ["quinn-proto/platform-verifier"]
